[project]
name = "fast-api"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Abdul Sahil", email = "sahiilwork444@gmail.com" }
]
requires-python = ">=3.14"
dependencies = [
    "fastapi[standard]>=0.143.0",
    "pyd>=0.13.1",
    "uvicorn>=0.54.0",
]

[project.scripts]
fastapi = "fastapi:main"

[build-system]
requires = ["uv_build>=0.12.22,<0.13.0"]
build-backend = "uv_build"
